server:
  port: 3344
spring:
  application:
    name: microservicecloud-config
  cloud:
    config:
      server:
        git:
          uri: https://github.com/lky492465798/microservicecloud-config.git
          username: xxxx
          password: xxxx
